

export const metadata = {
    title: "Articles Page",
    description: "Generated by create next app",
};
export default function ({children}) {
    return (
        <div>
            <h1>Articles Layout</h1>
          <div
            style={{
              display: "flex",
              justifyContent: "center",
              alignItems: "center",
              height: "100vh",
              color: "red",
              backgroundColor: "green"
            }}
          >{children}</div>  
        </div>
    );
}